<a href="https://colab.research.google.com/github/Pin-Han/ML_lession/blob/lesson_3/regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the libiraries

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing the dataset

In [7]:
dataset=pd.read_csv('Data.csv')
x = dataset.iloc[:,  :-1].values #第一個 : 是選擇所有行，第二個 :-1 是所有列(但撇除最右邊的那列)
y = dataset.iloc[:,  -1].values #取最後一行內容

In [8]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [9]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


Taking care of missing data

In [10]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# 尋找 Nan (np.nan)，替換策略為 mean。 mean 為 非缺失值得平均值

imputer.fit(x[:,1:3]) # fit() 為計算數據統計量
x[:, 1:3]=imputer.transform(x[:, 1:3]) # transform() 為將統計量替換到實際數據上


In [ ]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Encoding categorical data

In [11]:
from sklearn.compose import ColumnTransformer # 用來創建一個列轉換器對象的 class，指定對數據集中的特定列進行特定的處理
from sklearn.preprocessing import OneHotEncoder # 這是一個列表，列表中的每個元素都是一個元組（tuple），用來指定對特定列應用哪種轉換器

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')

# transformers 這是一個列表，列表中的每個元素都是一個元組（tuple），用來指定對特定列應用哪種轉換器
# 只有一個元組 ('encoder', OneHotEncoder(), [0])：'encoder' 是這個轉換器的名稱，這個名字是任意的，用於標識和參考轉換器。
# OneHotEncoder() 是轉換器對象，這裡應用了 OneHotEncoder 來對指定列進行一位有效編碼。
# [0] 指定了要轉換的列的索引，這裡是數據集中的第一列，即 Country
# 這個參數設定了對於未在 transformers 列表中明確指定的列應該怎麼處理。'passthrough' 表示除了在 transformers 中指定的列之外，其他所有列都會不經修改地“通過”到輸出數據中。這保證了數據集中未經轉換的部分仍然保留在最終處理後的數據集中

x = np.array(ct.fit_transform(x))

print(x)


[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


Encoding the dependent variable

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


Splitting the dataset into the Training set and Test set

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)
#random_state=1 是一個控制隨機數生成的參數，確保每次執行代碼時，數據的隨機分割方式保持一致。這在實驗的可重現性方面非常重要。



In [16]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [17]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [18]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [19]:
print(y_test)

[0 1]


Feature scaling